site_name: 日常学习帮助网站
use_directory_urls: false

theme:
  name: 'material'
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/git-alt
  language: zh
  primary: red
  accent: light blue
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

copyright: Copyright &copy; 2024 EPSDA

nav:
  - 主页: index.md
  - C语言:
    - C语言基础知识: C语言/1. C语言基础知识/1. C语言基础知识.md
    - 进制转换与类型在内存的存储方式: C语言/2. 进制转换与类型在内存中存储方式/2. 进制转换与类型在内存中存储方式.md
    - C语言数据类型与变量: C语言/3. C语言数据类型和变量/3. C语言数据类型和变量.md
    - C语言操作符: C语言/4. C语言操作符/4. C语言操作符.md
    - C语言的标准输入函数scanf及标准输出函数printf: C语言/5. C语言的标准输入函数scanf及标准输出函数printf/5. C语言的标准输入函数scanf及标准输出函数printf.md
    - C语言中的分支语句: C语言/6. C语言中的分支语句/6. C语言中的分支语句.md
    - C语言中的循环语句: C语言/7. C语言中的循环语句/7. C语言中的循环语句.md
    - C语言函数: C语言/8. C语言函数/8. C语言函数.md
    - C语言指针: C语言/9. C语言指针/9. C语言指针.md
    - C语言字符函数、字符串函数与内存函数: C语言/10. C语言字符函数、字符串函数与内存函数/10. C语言字符函数、字符串函数与内存函数.md
    - C语言动态内存管理: C语言/11. C语言动态内存管理/11. C语言动态内存管理.md
    - C语言文件操作: C语言/12. C语言文件操作/12. C语言文件操作.md
    - C语言编译与链接（基础）: C语言/13. C语言编译与链接（基础）/13. C语言编译与链接（基础）.md
    - C语言预处理（部分）: C语言/14. C语言预处理（部分）/14. C语言预处理（部分）.md
  - 数据结构:
    - 时间复杂度和空间复杂度: 数据结构/1. 时间复杂度和空间复杂度/1. 时间复杂度与空间复杂度.md
  - C++: 
    - C语言过渡C++基础知识: C++/1. C语言过渡C++基础知识/1. C语言过渡C++基础知识.md
  - Linux:
    - Linux常用选项和指令: Linux/1. Linux常用选项和指令/1. Linux常用选项和指令.md
  - 算法:
    - 双指针算法: 算法/1. 双指针算法/1. 双指针算法.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true  # 启用行号显示
      anchor_linenums: true
  - toc:
      permalink: true
      baselevel: 1  # 开始级别
      toc_depth: 6  # 最大深度
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/H0308

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

repo_url: https://github.com/H0308/HelperSite
repo_name: H0308/HelperSite