site_name: 日常学习帮助网站
use_directory_urls: false

theme:
  name: 'material'
  features:
  - header.autohide

nav:
  - 主页: index.md
  - C语言教程: 
    - C语言基础知识: 1. C语言基础知识/1. C语言基础知识.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences