site_name: 柯懒的知识库
site_url: https://www.help-doc.top
use_directory_urls: false

theme:
  name: 'material'
  font: false
  custom_dir: overrides
  favicon: images/favicon.png
  logo: assets/logo.png
  features:
    - navigation.indexes
    - navigation.prune
    - navigation.tabs 
    - search.highlight
    - content.code.copy
  language: zh
  palette:
    - scheme: default
      accent: cyan
      primary: white

copyright: Copyright &copy; 2024-2025 柯懒不是柯南

nav:
  - 主页: index.md
  - 网站介绍: intro/intro.md
  - 网站时间线: timeline/timeline.md
  - 编程语言:
    - C语言:
      - 章节目录: c-lang/index.md
      - C语言基础知识: c-lang/c-base/c-base.md
      - 进制转换与类型在内存的存储方式: c-lang/num-in-memory/num-in-memory.md
      - C语言数据类型与变量: c-lang/var-type/var-type.md
      - C语言操作符: c-lang/op/op.md
      - C语言的标准输入函数scanf及标准输出函数printf: c-lang/scanf-printf/scanf-printf.md
      - C语言中的分支语句: c-lang/branch-line/branch-line.md
      - C语言中的循环语句: c-lang/cycle-line/cycle-line.md
      - C语言函数: c-lang/func/func.md
      - C语言指针: c-lang/ptr/ptr.md
      - C语言字符函数、字符串函数与内存函数: c-lang/char-str-func/char-str-func.md
      - C语言动态内存管理: c-lang/dynamic-memory/dynamic-memory.md
      - C语言文件操作: c-lang/fileop/fileop.md
      - C语言编译与链接（基础）: c-lang/compile-link/compile-link.md
      - C语言预处理（部分）: c-lang/preprocess/preprocess.md
    - C++: 
      - 章节目录: cpp/index.md
      - C语言过渡C++基础知识: cpp/c-to-cpp/c-to-cpp.md
      - C++类和对象: cpp/class-obj/class-obj.md
      - C++默认成员函数: cpp/member-func/member-func.md
      - C++类和对象相关内容: cpp/class-obj-other/class-obj-other.md
      - C++内存管理: cpp/memory/memory.md
      - C++模版: cpp/template/template.md
      - C++STL简介与string类: cpp/stl-intro-string/stl-intro-string.md
      - string类模拟实现: cpp/sim-string/sim-string.md
      - vector类: cpp/vector/vector.md
      - vector类模拟实现: cpp/sim-vector/sim-vector.md
      - list类: cpp/list/list.md
      - list类模拟实现: cpp/sim-list/sim-list.md
      - stack类: cpp/stack/stack.md
      - queue与priority_queue类: cpp/queue-priority-queue/queue-priority-queue.md
      - stack和queue模拟实现: cpp/sim-stack-queue/sim-stack-queue.md
      - priority_queue模拟实现: cpp/sim-priority-queue/sim-priority-queue.md
      - 反向迭代器设计: cpp/reverse-iterator/reverse-iterator.md
      - C++继承: cpp/extend/extend.md
      - C++多态: cpp/polymorphic/polymorphic.md
      - set类: cpp/set/set.md
      - map类: cpp/map/map.md
      - map和set类模拟实现: cpp/sim-map-set/sim-map-set.md
      - unordered_map和unordered_set类模拟实现: cpp/sim-unordered-map-set/sim-unordered-map-set.md
      - bitset类: cpp/bitset/bitset.md
      - initializer_list类: cpp/initializer-list/initializer-list.md
      - C++ 11相关新特性: cpp/new-in-cpp11/new-in-cpp11.md
      - C++异常: cpp/exception/exception.md
      - C++智能指针: cpp/smart-ptr/smart-ptr.md
      - 特殊类设计: cpp/special-class-design/special-class-design.md
      - C++中的类型转换: cpp/type-cast/type-cast.md
      - C++ IO流: cpp/cppio/cppio.md
      - C++ 17相关新特性: cpp/new-in-cpp17/new-in-cpp17.md
      - C++时间和随机数相关库: cpp/time-rand/time-rand.md
      - C++并发支持库: cpp/multi-thread/multi-thread.md
      - C++中的格式化字符串: cpp/format/format.md
    - Java:
      - Java基础知识: Java/java-basic/java-basic.md
      - Java数组类型: Java/java-array/java-array.md
      - Java面向对象与方法: Java/obj-oriented-and-method/obj-oriented-and-method.md
      - Java面向对象与封装: Java/obj-oriented-and-encapsulation/obj-oriented-and-encapsulation.md
      - Java面向对象与继承: Java/obj-oriented-and-inheritance/obj-oriented-and-inheritance.md
      - Java面向对象与接口: Java/obj-oriented-and-interface/obj-oriented-and-interface.md
      - Java面向对象与多态: Java/obj-oriented-and-polymorphic/obj-oriented-and-polymorphic.md
      - Java面向对象与权限修饰符、final、代码块及内部类: Java/permission-modifier-final-internal-class/permission-modifier-final-internal-class.md
      - Java异常类: Java/obj-oriented-and-exception/obj-oriented-and-exception.md
      - Java中的Object类和常用方法、经典接口: Java/object-class-method-interface/object-class-method-interface.md
      - Java.lang中的String类和StringBuilder类介绍和常用方法: Java/string-stringbuilder/string-stringbuilder.md
      - Java中的常用类及包装类: Java/common-class-packed-class/common-class-packed-class.md
      - Java中的泛型: Java/generic/generic.md
      - Java单列集合: Java/collection/collection.md
      - Java双列集合: Java/map/map.md
      - 了解Java字符串常量池: Java/string-constant-pool/string-constant-pool.md
      - Java多线程: Java/multi-thread/multi-thread.md
      - Java的IO流: Java/javaio/javaio.md
      - Java网络编程、正则表达式、设计模式与Lombok: Java/net-reg-design-lombok/net-reg-design-lombok.md
      - Java中的JDK8及后续的重要新特性: Java/new-jdk8-and-after/new-jdk8-and-after.md
      - Java中的Junit、类加载时机与机制、反射、注解及枚举: Java/junit-reflect-annotation-enum/junit-reflect-annotation-enum.md
      - （补充）JSON在后端的应用: Java/json-in-java/json-in-java.md
    - Python:
      - Python基础知识: python/python-basic/python-basic.md
      - Python组合数据类型: python/composite-data-type/composite-data-type.md
      - Python异常处理: python/exception/exception.md
      - Python函数: python/func/func.md
      - Python模块: python/module/module.md
      - Python输出与文件操作: python/output-format-fileop/output-format-fileop.md
      - Python类和对象基础: python/class-obj-basic/class-obj-basic.md
      - Python类和对象进阶: python/class-obj-advanced/class-obj-advanced.md
  - 数据结构与算法:
    - 数据结构:
      - 数据结构基础: data-structure/time-space-complexity/time-space-complexity.md
      - 顺序结构与顺序表: data-structure/sequential-structure-and-sequential-table/sequential-structure-and-sequential-table.md
      - 链表: data-structure/linked-list/linked-list.md
      - 栈: data-structure/stack/stack.md
      - 队列: data-structure/queue/queue.md
      - 树的基本概念: data-structure/tree-basic-concept/tree-basic-concept.md
      - 二叉树（基础）: data-structure/binary-tree/binary-tree.md
      - 堆: data-structure/heap/heap.md
      - 排序: data-structure/sort/sort.md
      - 二叉搜索树: data-structure/binary-search-tree/binary-search-tree.md
      - AVL树: data-structure/avl-tree/avl-tree.md
      - 红黑树: data-structure/red-black-tree/red-black-tree.md
      - 哈希表: data-structure/hash-table/hash-table.md
      - 位图: data-structure/bitset/bitset.md
      - 布隆过滤器与海量数据处理: data-structure/bloom-filter/bloom-filter.md
    - 算法:
      - 算法比赛常用内容: algorithm/common/common.md
      - 数组基础篇:
        - 数组理论基础: algorithm/array-basic/array-concept/array-concept.md
        - 二分查找: algorithm/array-basic/binary-search/binary-search.md
        - 移除元素（双指针基础）: algorithm/array-basic/remove-element/remove-element.md
        - 滑动窗口: algorithm/array-basic/sliding-window/sliding-window.md
        - 前缀和: algorithm/array-basic/prefix-sum/prefix-sum.md
        - 模拟: algorithm/array-basic/simulation/simulation.md
        - 位运算: algorithm/array-basic/bit-operation/bit-operation.md
      - 链表篇:
        - 链表理论基础: algorithm/list/list-concept/list-concept.md
        - 链表基础练习: algorithm/list/list-basic/list-basic.md
        - 链表进阶练习: algorithm/list/list-advanced/list-advanced.md
      - 哈希表篇:
        - 哈希表理论基础: algorithm/hash-table/hash-table-concept/hash-table-concept.md
        - 哈希表基础练习: algorithm/hash-table/hash-table-basic/hash-table-basic.md
        - 哈希表进阶练习: algorithm/hash-table/hash-table-advanced/hash-table-advanced.md
      - 字符串篇:
        - 字符串基础练习: algorithm/string/string-basic/string-basic.md
        - 字符串进阶练习: algorithm/string/string-advanced/string-advanced.md
      - 双指针: algorithm/two-pointers/two-pointers.md
      - 栈和队列篇:
        - 栈和队列理论基础: algorithm/stack-queue/stack-queue-concept/stack-queue-concept.md
        - 栈和队列基础练习: algorithm/stack-queue/stack-queue-basic/stack-queue-basic.md
      - 递归与二叉树篇:
        - 递归介绍: algorithm/recursion-binary-tree/recursion-intro/recursion-intro.md
        - 二叉树理论基础: algorithm/recursion-binary-tree/binary-tree-concept/binary-tree-concept.md
        - 二叉树遍历相关题目: algorithm/recursion-binary-tree/binary-tree-traversal/binary-tree-traversal.md
        - 二叉树基础题目: algorithm/recursion-binary-tree/binary-tree-basic/binary-tree-basic.md
        - 二叉搜索树相关题目: algorithm/recursion-binary-tree/binary-tree-bst/binary-tree-bst.md
        - 常规题目中的递归: algorithm/recursion-binary-tree/recursion-in-regular/recursion-in-regular.md
      - 回溯篇:
        - 回溯理论基础: algorithm/backtracking/backtracking-concept/backtracking-concept.md
        - 回溯基础练习: algorithm/backtracking/backtracking-basic/backtracking-basic.md
        - 回溯进阶练习: algorithm/backtracking/backtracking-advanced/backtracking-advanced.md
      - 贪心篇:
        - 贪心理论基础: algorithm/greedy/greedy-concept/greedy-concept.md
        - 贪心基础练习: algorithm/greedy/greedy-basic/greedy-basic.md
      - 动态规划篇:
        - 动态规划理论基础: algorithm/dp/dp-concept/dp-concept.md
      - 其他算法:
        - KMP算法: algorithm/other/kmp/kmp.md
        - 波兰表达式与逆波兰表达式: algorithm/other/polish-notation/polish-notation.md
        - 霍尔法则: algorithm/other/hall/hall.md
        - 数字和与数字根: algorithm/other/number-sum/number-sum.md
        - 最大公因数和最小公倍数: algorithm/other/gcd-lcm/gcd-lcm.md
        - 大数运算: algorithm/other/big-number-op/big-number-op.md
        - 取模与取余: algorithm/other/modulo/modulo.md
  - Linux:
    - Linux常用选项和指令: Linux/1. Linux常用选项和指令/1. Linux常用选项和指令.md
    - Linux权限相关: Linux/2. Linux权限相关/2. Linux权限相关.md
    - CentOS软件安装: Linux/3. CentOS软件安装/3. CentOS软件安装.md
    - Linux下的gcc与gdb: Linux/4. Linux下的gcc与gdb/4. Linux下的gcc与gdb.md
    - Linux下的Makefile与进度条程序: Linux/5. Linux下的Makefile与进度条程序/5. Linux下的Makefile与进度条程序.md
    - 操作系统基础知识: Linux/6. 操作系统基础知识/6. 操作系统基础知识.md
    - Linux进程基础: Linux/7. Linux进程/7. Linux进程.md
    - Linux进程状态与进程优先级: Linux/8. Linux进程状态与进程优先级/8. Linux进程状态与进程优先级.md
    - Linux进程切换以及调度算法: Linux/9. Linux进程切换以及调度算法/9. Linux进程切换以及调度算法.md
    - Linux命令行与环境变量: Linux/10. Linux命令行与环境变量/10. Linux命令行与环境变量.md
    - Linux进程地址空间: Linux/11. Linux进程地址空间/11. 进程地址空间.md
    - Linux进程控制: Linux/12. Linux进程控制/12. Linux进程控制.md
    - Linux文件操作基础: Linux/13. Linux文件操作基础/13. Linux文件操作基础.md
    - Linux中输入和输出基本过程: Linux/14. Linux中输入和输出基本过程/14. Linux中输入和输出基本过程.md
    - Linux文件系统: Linux/15. Linux文件系统/15. Linux文件系统.md
    - Linux软链接和硬链接: Linux/16. Linux软链接和硬链接/16. Linux软链接和硬链接.md
    - Linux进程间通信: 
      - 进程间通信介绍与匿名管道: Linux/17. Linux进程间通信/1. 进程间通信介绍与匿名管道/1. 进程间通信介绍与匿名管道.md
      - 命名管道与共享内存: Linux/17. Linux进程间通信/2. 命名管道与共享内存/2. 命名管道与共享内存.md
      - 消息队列与信号量: Linux/17. Linux进程间通信/3. 消息队列和信号量/3. 消息队列和信号量.md
      - 操作系统管理System V标准中三种资源的方式: Linux/17. Linux进程间通信/4. 操作系统管理System V标准中三种资源的方式/4. 操作系统管理System V标准中三种资源的方式.md
    - Linux信号与操作系统原理: Linux/18. Linux信号与操作系统原理/18. Linux信号与操作系统原理.md
    - Linux线程:
      - Linux线程概念与线程操作: Linux/19. Linux线程/1. Linux线程概念与线程操作/1. Linux线程概念与线程操作.md
      - Linux线程库与线程库封装: Linux/19. Linux线程/2. Linux线程库与线程库封装/2. Linux线程库与线程库封装.md
      - Linux线程互斥与同步: Linux/19. Linux线程/3. Linux线程同步与互斥/3. Linux线程同步与互斥.md
      - Linux线程与信号量: Linux/19. Linux线程/4. Linux线程与信号量/4. Linux线程与信号量.md
      - 生产者消费者模型（Producer-Consumer Model）: Linux/19. Linux线程/5. 生产者消费者模型（Producer-Consumer Model）/5. 生产者消费者模型（Producer-Consumer Model）.md
      - 日志系统: Linux/19. Linux线程/6. 日志系统/6. 日志系统.md
      - Linux线程安全与死锁: Linux/19. Linux线程/7. Linux线程安全与死锁/7. Linux线程安全与死锁.md
      - Linux线程池: Linux/19. Linux线程/8. Linux线程池/8. Linux线程池.md
      - 读者写者问题与读写锁: Linux/19. Linux线程/9. 读者写者问题与读写锁/9. 读者写者问题与读写锁.md
      - 自旋锁: Linux/19. Linux线程/10. 自旋锁/10. 自旋锁.md
    - 网络基础知识: Linux/20. 网络基础知识/20. 网络基础知识.md
    - Socket编程基础: Linux/21. Socket编程基础/21. Socket编程基础.md
    - UDP编程:
      - UDP编程接口基本使用: Linux/22. UDP编程/1. UDP编程接口基本使用/1. UDP编程接口基本使用.md
      - UDP应用1：翻译软件: Linux/22. UDP编程/2. UDP应用1：翻译软件/2. UDP应用1：翻译软件.md
      - UDP应用2：简易聊天室: Linux/22. UDP编程/3. UDP应用2：简易聊天室/3. UDP应用2：简易聊天室.md
    - TCP编程接口基本使用: Linux/23. TCP编程接口基本使用/23. TCP编程接口基本使用.md
    - 序列化和反序列化与网络计算器: Linux/24. 序列化问题与网络计算器/24. 序列化问题与网络计算器.md
    - 进程间关系和守护进程: Linux/25. 进程间关系和守护进程/25. 进程间关系和守护进程.md
    - 应用层协议HTTP:
      - 介绍HTTP协议基本结构与基本实现HTTPServer: Linux/26. 应用层协议HTTP/1. 介绍HTTP协议基本结构与基本实现HTTPServer/1. 介绍HTTP协议基本结构与基本实现HTTPServer.md
      - 深入HTTP序列化和反序列化: Linux/26. 应用层协议HTTP/2. 深入HTTP序列化和反序列化/2. 深入HTTP序列化和反序列化.md
      - HTTP报头属性和请求方式: Linux/26. 应用层协议HTTP/3. HTTP报头属性和请求方式/3. HTTP报头属性和请求方式.md
      - HTTP中的Cookie和Session: Linux/26. 应用层协议HTTP/4. HTTP中的Cookie和Session/4. HTTP中的Cookie和Session.md
      - HTTP版本介绍: Linux/26. 应用层协议HTTP/5. HTTP版本介绍/5. HTTP版本介绍.md
      - HTTPS协议介绍与原理: Linux/26. 应用层协议HTTP/6. HTTPS协议介绍与原理/6. HTTPS协议介绍与原理.md
    - UDP协议原理: Linux/27. UDP协议原理/27. UDP协议原理.md
    - TCP协议原理: Linux/28. TCP协议原理/28. TCP协议原理.md
    - 理解Linux如何看待连接以及TCP全连接队列: Linux/35. 理解Linux如何看待连接以及TCP全连接队列/35. 理解Linux如何看待连接以及TCP全连接队列.md
    - 网络层IP协议: Linux/29. 网络层IP协议/29. 网络层IP协议.md
    - 数据链路层协议: Linux/30. 数据链路层协议/30. 数据链路层协议.md
    - DNS与ICMP: Linux/36. DNS与ICMP/36. DNS与ICMP.md
    - NAT技术、代理服务器和内网穿透: Linux/31. NAT技术、代理服务器和内网穿透/31. NAT技术、代理服务器和内网穿透.md
    - 五种IO模型与select和poll分别实现多路转接: Linux/32. 五种IO模型与select和poll分别实现多路转接/32. 五种IO模型与select和poll分别实现多路转接.md
    - epoll实现多路转接: Linux/33. epoll实现多路转接/33. epoll实现多路转接.md
    - Reactor模式与完善基于边缘触发模式epoll实现TCP服务器: Linux/34. Reactor模式与完善基于边缘触发模式epoll实现TCP服务器/34. Reactor模式与完善基于边缘触发模式epoll实现TCP服务器.md
  - 前端:
    - HTML与CSS:
      - HTML4和HTML5常见标签总结: HTML与CSS/HTML笔记/HTML笔记.md
      - CSS2笔记: HTML与CSS/CSS2笔记/CSS2笔记.md
      - HTML与CSS基础知识笔记: HTML与CSS/HTML与CSS.md
      - HTML与CSS中的Emmet表达式: HTML与CSS/Emmet表达式/Emmet表达式.md
    - JavaScript:
      - JavaScript语法基础:
        - JavaScript基本语法: JavaScript基础知识/1. JavaScript基础/JavaScript基础.md
        - JavaScript对象基础: JavaScript基础知识/2. JavaScript对象基础/2. JavaScript对象基础.md
        - JavaScript函数: JavaScript基础知识/3. JavaScript函数/3. JavaScript函数.md
        - JavaScript面向对象: JavaScript基础知识/4. JavaScript面向对象/4. JavaScript面向对象.md
        - JavaScript数组: JavaScript基础知识/5. JavaScript数组/5. JavaScript数组.md
        - JavaScript内建对象: JavaScript基础知识/6. JavaScript内建对象/6. JavaScript内建对象.md
      - JavaScript与DOM和BOM操作:
        - DOM和BOM介绍: JavaScript基础知识/7. DOM和BOM介绍/7. DOM和BOM介绍.md
        - DOM操作: JavaScript基础知识/8. JavaScript与DOM操作/8. JavaScript与DOM操作.md
        - BOM操作: JavaScript基础知识/9. JavaScript与BOM操作/9. JavaScript与BOM操作.md
        - DOM和BOM小练习: JavaScript基础知识/11. （附加）DOM和BOM小练习/11. （附加）DOM和BOM小练习.md
      - JavaScript与JQuery（了解）: JavaScript基础知识/10. JavaScript与JQuery/10. JavaScript与JQuery.md
    - Vue:
      - Vue前置知识: vue基础知识/1. vue前置知识/1. vue前置知识.md
      - Vue基础与响应式: vue基础知识/2. vue的响应式基础/2. vue的响应式基础.md
      - Vue的基本结构: vue基础知识/3. vue的基本结构/3. vue的基本结构.md
      - 从新结构再看响应式基础: vue基础知识/4. 从新结构再看响应式基础/4. 从新结构再看响应式基础.md
      - Vue基础指令: vue基础知识/5. vue基础指令/5. vue基础指令.md
      - Vue组件介绍与生命周期: vue基础知识/6.vue组件介绍与生命周期/6. vue组件介绍与生命周期.md
    - Qt:
      - Qt环境准备与基础代码解释: Qt基础知识/1. Qt介绍与基础代码解释/1. Qt介绍与基础代码解释.md
  - MySQL:
    - MySQL基础: MySQL/MySQL基础使用/MySQL基础使用.md
    - JDBC（Java连接数据库技术）:
      - JDBC基础: MySQL/JDBC/JDBC基础/JDBC基础.md
      - JDBC进阶: MySQL/JDBC/JDBC进阶/JDBC进阶.md
      - JDBC高级: MySQL/JDBC/JDBC高级/JDBC高级.md
    - MySQL基础知识:
      - MySQL基础操作: MySQL/MySQL基础知识/2. MySQL基础操作/2. MySQL基础操作.md
      - （补充）Ubuntu下安装和卸载MySQL: MySQL/MySQL基础知识/1. Ubuntu下安装和卸载MySQL/1. Ubuntu下安装和卸载MySQL.md
  - JavaEE应用开发:
    - SpringMVC基础: JavaEE/Spring/1. SpringMVC基础/1. SpringMVC基础.md
  - 扩展知识: 
    - 关于Shell: 其它/Shell脚本语言/关于Shell.md
    - 关于函数栈帧（C语言演示）: 其它/C语言函数栈帧/关于函数栈帧（C语言演示）.md
    - 关于xml文件: 其它/关于xml文件/关于xml文件.md
    - 关于JSONCPP库: 其它/关于JSONCPP库/关于JSONCPP库.md
    - 关于C++日志库spdlog: 其它/关于C++日志库spdlog/关于C++日志库spdlog.md
    - 关于Git: 
      - Git基础操作: 其它/关于Git/Git基础操作/Git基础操作.md
      - Git多人协作: 其它/关于Git/Git多人协作/Git多人协作.md
    - 关于Muduo库: 其它/关于Muduo库/关于Muduo库.md
  - 工具帮助:
    - vscode中添加代码片段: 工具帮助/vscode中添加代码片段/vscode中添加代码片段.md
    - Windows系统下在VMware中配置Linux环境并通过客户端进行连接: 工具帮助/Windows系统下在VMware中配置Linux环境并通过客户端进行连接/Windows系统下在VMware中配置Linux环境并通过客户端进行连接.md
    - Sunshine+Moonlight实现屏幕内容串流: 工具帮助/Sunshine+Moonlight实现屏幕内容串流/Sunshine+Moonlight实现屏幕内容串流.md
    - vim使用帮助: 工具帮助/vim使用帮助/vim使用帮助.md
  - 项目:
    - Boost库搜索引擎: 项目/1. Boost库搜索引擎/1. Boost库搜索引擎.md
    - 仿Muduo库的高并发服务器: 
      - 项目介绍与准备: 项目/3. 仿Muduo库的高并发服务器/1. 项目介绍与准备/1. 项目介绍与准备.md
      - 服务器底层模块设计: 项目/3. 仿Muduo库的高并发服务器/2. 服务器底层模块设计/2. 服务器底层模块设计.md
    - 基于JSON的RPC框架:
      - 项目介绍与准备: 项目/2. 基于JSON的RPC框架/1. 项目介绍与准备/1. 项目介绍与准备.md
      - 基础模块设计: 项目/2. 基于JSON的RPC框架/2. 基础模块设计/2. 基础模块设计.md
      - 功能模块设计（RPC、注册）: 项目/2. 基于JSON的RPC框架/3. 功能模块设计（RPC、注册）/3. 功能模块设计（RPC、注册）.md
      - 功能模块设计（主题、客户端封装、服务端封装）: 项目/2. 基于JSON的RPC框架/5. 功能模块设计（主题、客户端封装、服务端封装）/5. 功能模块设计（主题、客户端封装、服务端封装）.md
      - 功能测试: 项目/2. 基于JSON的RPC框架/4. 功能测试/4. 功能测试.md

not_in_nav: |
  JavaWeb/2. Servlet开发/2. Servlet开发.md
  JavaWeb/3. 乱码问题和路径问题/3. 乱码问题和路径问题.md
  JavaWeb/5. 会话、过滤器和监听器/5. 会话、过滤器和监听器.md
  工具帮助/Tomcat安装和使用/Tomcat安装和使用.md
  作者/关于作者/关于作者.md
  作者/联系作者/作者.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true  # 启用行号显示
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      use_pygments: true
      pygments_style: sas
  - toc:
      permalink: true
      baselevel: 1  # 开始级别
      toc_depth: 6  # 最大深度
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/katex.js
  - javascripts/other.js
  - javascripts/copyright.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css

extra:
  extra:
  analytics:
    provider: google
    property: G-9XWRGNRRSY
    feedback:
      title: 页面有帮助吗？
      ratings:
        - icon: material/thumb-up-outline
          name: 页面对我有帮助
          data: 1
          note: >-
            谢谢你的反馈！
        - icon: material/thumb-down-outline
          name: 页面没有帮助到我
          data: 0
          note: >- 
            谢谢你的反馈！联系<a href="https://www.help-doc.top/%E4%BD%9C%E8%80%85/%E4%BD%9C%E8%80%85.html">作者</a>提供更详细的信息
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/H0308
    - icon: fontawesome/brands/qq
      link: https://www.help-doc.top/%E4%BD%9C%E8%80%85/%E4%BD%9C%E8%80%85.html
  generator: false
      
plugins:
  - search:
      jieba_dict: dict.txt.small
      lang: zh
  - statistics
  - toggle-sidebar
  - changelog
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      js_files:
          - javascripts/katex.js
          - javascripts/other.js
          - javascripts/copyright.js
          - javascripts/start.js
          - javascripts/waline.js
      css_files:
        - stylesheets/code-font-dejavu-sans-mono.css
        - stylesheets/code-font-zsft-hk.css
        - stylesheets/font-dongguanti.css
        - stylesheets/font-oppoti.css
        - stylesheets/font-jiangchengti.css
        - stylesheets/font-lxgw.css
        - stylesheets/colors.css
        - stylesheets/theme1.css
        - stylesheets/theme2.css
        - stylesheets/print.css
        - stylesheets/waline.css
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      exclude:
        - index.md
        - 作者/联系作者/作者.md
        - 网站介绍/网站介绍.md