site_name: 日常学习帮助网站
use_directory_urls: false

theme:
  name: 'material'
  features:
  - header.autohide

nav:
  - 主页: index.md
  - C语言教程: 
    - C语言基础知识: 1. C语言基础知识/1. C语言基础知识.md

markdown_extensions:
  - abbr

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

markdown_extensions:
  - pymdownx.highlight:
      linenums: true

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx.inline

markdown_extensions:
  - pymdownx.keys

markdown_extensions:
  - pymdownx.snippets